/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterAccountRouteImport } from './routes/register-account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutKnowledgeBaseIndexRouteImport } from './routes/_layout/knowledge-base/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard/index'
import { Route as LayoutAccountIndexRouteImport } from './routes/_layout/account/index'
import { Route as LayoutKnowledgeBaseNewRouteImport } from './routes/_layout/knowledge-base/new'
import { Route as LayoutKnowledgeBaseKbIdIndexRouteImport } from './routes/_layout/knowledge-base/$kbId/index'

const RegisterAccountRoute = RegisterAccountRouteImport.update({
  id: '/register-account',
  path: '/register-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutKnowledgeBaseIndexRoute =
  LayoutKnowledgeBaseIndexRouteImport.update({
    id: '/knowledge-base/',
    path: '/knowledge-base/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountIndexRoute = LayoutAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBaseNewRoute = LayoutKnowledgeBaseNewRouteImport.update({
  id: '/knowledge-base/new',
  path: '/knowledge-base/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBaseKbIdIndexRoute =
  LayoutKnowledgeBaseKbIdIndexRouteImport.update({
    id: '/knowledge-base/$kbId/',
    path: '/knowledge-base/$kbId/',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register-account': typeof RegisterAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/knowledge-base/new': typeof LayoutKnowledgeBaseNewRoute
  '/account': typeof LayoutAccountIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseIndexRoute
  '/knowledge-base/$kbId': typeof LayoutKnowledgeBaseKbIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register-account': typeof RegisterAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/knowledge-base/new': typeof LayoutKnowledgeBaseNewRoute
  '/account': typeof LayoutAccountIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseIndexRoute
  '/knowledge-base/$kbId': typeof LayoutKnowledgeBaseKbIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register-account': typeof RegisterAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_layout/knowledge-base/new': typeof LayoutKnowledgeBaseNewRoute
  '/_layout/account/': typeof LayoutAccountIndexRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/knowledge-base/': typeof LayoutKnowledgeBaseIndexRoute
  '/_layout/knowledge-base/$kbId/': typeof LayoutKnowledgeBaseKbIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register-account'
    | '/auth/callback'
    | '/knowledge-base/new'
    | '/account'
    | '/dashboard'
    | '/knowledge-base'
    | '/knowledge-base/$kbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register-account'
    | '/auth/callback'
    | '/knowledge-base/new'
    | '/account'
    | '/dashboard'
    | '/knowledge-base'
    | '/knowledge-base/$kbId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/register-account'
    | '/auth/callback'
    | '/_layout/knowledge-base/new'
    | '/_layout/account/'
    | '/_layout/dashboard/'
    | '/_layout/knowledge-base/'
    | '/_layout/knowledge-base/$kbId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterAccountRoute: typeof RegisterAccountRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-account': {
      id: '/register-account'
      path: '/register-account'
      fullPath: '/register-account'
      preLoaderRoute: typeof RegisterAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/knowledge-base/': {
      id: '/_layout/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof LayoutKnowledgeBaseIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/': {
      id: '/_layout/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAccountIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-base/new': {
      id: '/_layout/knowledge-base/new'
      path: '/knowledge-base/new'
      fullPath: '/knowledge-base/new'
      preLoaderRoute: typeof LayoutKnowledgeBaseNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-base/$kbId/': {
      id: '/_layout/knowledge-base/$kbId/'
      path: '/knowledge-base/$kbId'
      fullPath: '/knowledge-base/$kbId'
      preLoaderRoute: typeof LayoutKnowledgeBaseKbIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutKnowledgeBaseNewRoute: typeof LayoutKnowledgeBaseNewRoute
  LayoutAccountIndexRoute: typeof LayoutAccountIndexRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutKnowledgeBaseIndexRoute: typeof LayoutKnowledgeBaseIndexRoute
  LayoutKnowledgeBaseKbIdIndexRoute: typeof LayoutKnowledgeBaseKbIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutKnowledgeBaseNewRoute: LayoutKnowledgeBaseNewRoute,
  LayoutAccountIndexRoute: LayoutAccountIndexRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutKnowledgeBaseIndexRoute: LayoutKnowledgeBaseIndexRoute,
  LayoutKnowledgeBaseKbIdIndexRoute: LayoutKnowledgeBaseKbIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterAccountRoute: RegisterAccountRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
