/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutKnowledgeBaseIndexRouteImport } from './routes/_layout/knowledge-base/index'
import { Route as LayoutChatIndexRouteImport } from './routes/_layout/chat/index'
import { Route as LayoutAccountIndexRouteImport } from './routes/_layout/account/index'
import { Route as LayoutChatSessionIdIndexRouteImport } from './routes/_layout/chat/$sessionId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutKnowledgeBaseIndexRoute =
  LayoutKnowledgeBaseIndexRouteImport.update({
    id: '/knowledge-base/',
    path: '/knowledge-base/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutChatIndexRoute = LayoutChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountIndexRoute = LayoutAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatSessionIdIndexRoute =
  LayoutChatSessionIdIndexRouteImport.update({
    id: '/chat/$sessionId/',
    path: '/chat/$sessionId/',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account': typeof LayoutAccountIndexRoute
  '/chat': typeof LayoutChatIndexRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseIndexRoute
  '/chat/$sessionId': typeof LayoutChatSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account': typeof LayoutAccountIndexRoute
  '/chat': typeof LayoutChatIndexRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseIndexRoute
  '/chat/$sessionId': typeof LayoutChatSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_layout/account/': typeof LayoutAccountIndexRoute
  '/_layout/chat/': typeof LayoutChatIndexRoute
  '/_layout/knowledge-base/': typeof LayoutKnowledgeBaseIndexRoute
  '/_layout/chat/$sessionId/': typeof LayoutChatSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/account'
    | '/chat'
    | '/knowledge-base'
    | '/chat/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/account'
    | '/chat'
    | '/knowledge-base'
    | '/chat/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/auth/callback'
    | '/_layout/account/'
    | '/_layout/chat/'
    | '/_layout/knowledge-base/'
    | '/_layout/chat/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/knowledge-base/': {
      id: '/_layout/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof LayoutKnowledgeBaseIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat/': {
      id: '/_layout/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/': {
      id: '/_layout/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAccountIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat/$sessionId/': {
      id: '/_layout/chat/$sessionId/'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof LayoutChatSessionIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAccountIndexRoute: typeof LayoutAccountIndexRoute
  LayoutChatIndexRoute: typeof LayoutChatIndexRoute
  LayoutKnowledgeBaseIndexRoute: typeof LayoutKnowledgeBaseIndexRoute
  LayoutChatSessionIdIndexRoute: typeof LayoutChatSessionIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountIndexRoute: LayoutAccountIndexRoute,
  LayoutChatIndexRoute: LayoutChatIndexRoute,
  LayoutKnowledgeBaseIndexRoute: LayoutKnowledgeBaseIndexRoute,
  LayoutChatSessionIdIndexRoute: LayoutChatSessionIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
